apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-website
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
