replicaCount: 2

image:
  repository: 045940814242.dkr.ecr.us-west-2.amazonaws.com/demo-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
